container_commands:
  10_installcertbot:
    command: |
      "wget https://dl.eff.org/certbot-auto"
      "sudo mv certbot-auto /usr/local/bin/certbot-auto"
      "sudo chown root /usr/local/bin/certbot-auto"
      "sudo chmod 0755 /usr/local/bin/certbot-auto"
  20_getcert:
    command: 'sudo /usr/local/bin/certbot-auto --nginx --redirect --debug --non-interactive --email info@parishconnect.ca --agree-tos --standalone --domains ${certdomain} --keep-until-expiring --pre-hook "service nginx stop"'
  30_link:
    command: "sudo /usr/local/bin/certbot-auto update_symlinks"
